# increase history size
set -g history-limit 100000

# start with mouse mode enabled
set -g mouse on

# stop windows from changing names
set-option -g allow-rename off
setw -g automatic-rename off # rename window to reflect current program
set -g renumber-windows on  # renumber windows when a window is closed

# force Vi mode
# really you should export VISUAL or EDITOR environment variable, see manual
set -g status-keys vi
set -g mode-keys vi
set -g @shell_mode 'vi'

# replace C-b by C-a instead of using both prefixes set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g status-interval 1000     # redraw status line every 10 seconds

# disable status bar
set -g status off

# set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-kitty:Tc"

setw -g xterm-keys on
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -g focus-events on

set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on

set -g base-index 1         # start windows numbering at 1
setw -g pane-base-index 1   # make pane numbering consistent with windows

# split current window horizontally
# bind - split-window -v
# split current window vertically
# bind _ split-window -h

# pane navigation
# bind -r h select-pane -L  # move left
# bind -r j select-pane -D  # move down
# bind -r k select-pane -U  # move up
# bind -r l select-pane -R  # move right
# bind > swap-pane -D       # swap current pane with the next one
# bind < swap-pane -U       # swap current pane with the previous one

# pane resizing
# bind -r H resize-pane -L 2
# bind -r J resize-pane -D 2
# bind -r K resize-pane -U 2
# bind -r L resize-pane -R 2

# window navigation
bind Tab last-window        # move to last active window

# -- urlview -------------------------------------------------------------------
bind U run "cut -c3- ~/.tmux.conf | sh -s _urlview #{pane_id}"

# -- facebook pathpicker -------------------------------------------------------
bind F run "cut -c3- ~/.tmux.conf | sh -s _fpp #{pane_id}"

# copy to X11 clipboard
if -b 'command -v xsel > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xsel -i -b"'
if -b '! command -v xsel > /dev/null 2>&1 && command -v xclip > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xclip -i -selection clipboard >/dev/null 2>&1"'
# copy to Windows clipboard
# if -b 'command -v clip.exe > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | clip.exe"'
# if -b '[ -c /dev/clipboard ]' 'bind y run -b "tmux save-buffer - > /dev/clipboard"'

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# activity
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# set border color
set -g pane-active-border-style fg="#d54e53",bg=default

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'Morantron/tmux-fingers'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# Copy mode
unbind p
bind p paste-buffer
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -selection clipboard"
# bind-key -Tcopy-mode-vi Escape send -X cancel

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
